---
title: "Experiment 1: Data modelling"
author: "Massimiliano Canzi"
date: "20/02/2021"
output: html_document
---

```{r, message = F}
library(emmeans)
library(itsadug)
library(mgcv)
library(tidymv)
library(tidyverse)
```

```{r readr.1, message = FALSE, include = F}
ERP <- bind_rows(read_csv("../data/EXP1_pt1.csv"), 
                 read_csv("../data/EXP1_pt2.lmer.csv")) %>%
  filter(Block == "PRS") %>%
  filter(Cond == "target" | Cond == "control") %>%
  mutate(Subj = as.factor(Subj)) %>%
  filter(time >= -100 & time <= 400) %>%
  gather(electrode, amplitude, Fp1:T8, factor_key = TRUE) %>%
  mutate(time = as.numeric(as.character(format(round(time, 0), nsmall = 0))),
         Block = as.factor(Block))

names(ERP) <- c("subject", "block", "condition", "time", "electrode", "amplitude")
```

```{r readr.2, message = FALSE, include = F}
ERP %<>% mutate(time = as.factor(time), subject = as.factor(subject)) %>%
  group_by(subject, block, condition, electrode, time) %>% 
  summarise(amplitude.mean = mean(amplitude),) %>% 
  ungroup() %>% mutate(time = as.numeric(as.character(time)), 
                       amplitude.mean = as.numeric(amplitude.mean), 
                       electrode = as.factor(electrode)) %>%
  filter(amplitude.mean <= 20 & amplitude.mean >= -20) %>%
  mutate(amplitude.mean = as.numeric(format(round(amplitude.mean, 2), nsmall = 2)))
```

```{r, include = F}
F.gamms <- ERP %>% 
  select(subject, amplitude = amplitude.mean, condition, time, electrode) %>% 
  filter(electrode %in% c("F1", "F3", "F5", "FC1", "FC3", "FC5", "T7", 
                          "F2", "F4", "F6", "FC2", "FC4", "FC6", "T8")) %>% 
  filter(condition == "control" | condition == "target") %>% 
  mutate(hemisphere = if_else(electrode %in% c("F1", "F3", "F5", "FC1", "FC3", "FC5", "T7"), "Left Hemisphere", "Right Hemisphere"), 
         condition = as.ordered(condition)) %>% 
  mutate(hemi.cond = interaction(hemisphere, condition)) %>% 
  mutate(hemi.cond = as.ordered(hemi.cond))
contrasts(F.gamms$condition) <- "contr.treatment"
contrasts(F.gamms$hemi.cond) <- "contr.treatment"
```

```{r, warning = F}
hemi.model <- bam(amplitude ~ 
                     s(time, k = 40) + 
                     hemi.cond + 
                     s(time, by = hemi.cond, k = 50) +
                     s(time, subject, bs = "fs", m = 1) + 
                     s(time, electrode, bs = "fs", m = 1), 
                   method = "ML", data = F.gamms)
```

```{r, warning = F}
cond.model <- bam(amplitude ~ 
                     s(time, k = 40) + 
                     condition + 
                     s(time, by = condition, k = 50) +
                     s(time, subject, bs = "fs", m = 1) + 
                     s(time, electrode, bs = "fs", m = 1), 
                   method = "ML", data = F.gamms)
```

```{r, warning = F}
null.model <- bam(amplitude ~ 
                     s(time, k = 40) + 
                     #hemi.cond + 
                     #s(time, by = hemi.cond, k = 50) +
                     s(time, subject, bs = "fs", m = 1) + 
                     s(time, electrode, bs = "fs", m = 1), 
                   method = "ML", data = F.gamms)
```

```{r}
compareML(null.model, cond.model)
```

```{r}
compareML(cond.model, hemi.model)
```

```{r, warning = F}
hemi.model <- bam(amplitude ~ 
                     s(time, k = 40) + 
                     hemi.cond + 
                     s(time, by = hemi.cond, k = 50) +
                     s(time, subject, bs = "fs", m = 1) + 
                     s(time, electrode, bs = "fs", m = 1), 
                   method = "fREML", data = F.gamms)
```

```{r, echo = F}
plot_smooths(model = hemi.model, 
             series = time, 
             comparison = condition, 
             facet_terms = hemisphere,
             split = list(hemi.cond = c("hemisphere", "condition")), 
             exclude_random = TRUE) + 
  theme_minimal() + 
  theme(legend.position = "top", aspect.ratio = 1/1.4) + 
  geom_hline(yintercept = 0, linetype = "solid") + xlab("Time (in ms)") + 
  ylab("Amplitude (in muV)") + 
  geom_vline(xintercept = 0, linetype = "solid", width = 0.5) + 
  scale_color_manual(values = c("indianred3", "deepskyblue4"), 
                     name = "Experimental Condition", 
                     labels = c("Control", "Target")) +
  scale_fill_manual(values = c("indianred3", "deepskyblue4"), 
                     name = "Experimental Condition", 
                     labels = c("Control", "Target")) + 
  scale_linetype_manual(values = c("dashed", "solid"), 
                     name = "Experimental Condition", 
                     labels = c("Control", "Target"))
```
